### ISSUE TITLE
Add Support for GPT4ALL

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#10]
### Issue Description
Add support for GPT4ALL models to load and use

**Comment by Swarno-Coder** [comment]
Assign me. I want to work on this problem.

**Comment by neokd** [comment]
@Swarno-Coder Any updates

**Comment by neokd** [comment]
@Swarno-Coder Any updates on the issue?

**Comment by Gladwin001** [comment]
Can you assign this issue
