### ISSUE TITLE
UI: Rebuild button

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#101]
Allow user to make an rebuild button which triggers the builder and then rebuilds the database

**Comment by neokd** [comment]
@onkar-1432 if your doing an open source contribution u can work on the issue. Once KWOC starts i'll create separate issues to work on..

**Comment by onkar-1432** [comment]
Thanks for replying. By that time I will understand the flow will start contributing after 9th December.

**Comment by I-MirzaBaig** [comment]
can i work on this?

**Comment by neokd** [comment]
Yeah @I-MirzaBaig
