### ISSUE TITLE
UI: Streamlit

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#104]
Currently, NeoGPT configurations are set through the CLI, requiring users to enter commands manually to specify device types, vector databases, retrievers, personas, etc. This process might be less intuitive for users who prefer a graphical interface.

Proposed Changes
Enhance manager.py: Integrate the UI with the manager.py file to process user inputs and initiate NeoGPT with the specified configurations.

Dynamic Retrievers and Databases: Enable users to choose and load different retrievers and databases directly from the UI, providing flexibility in their interactions with NeoGPT.

**Comment by StatKumar** [comment]
@neokd Can I work on this issue?

**Comment by neokd** [comment]
@StatKumar sure you can work on it

**Comment by StatKumar** [comment]
Thank you @neokd

**Comment by savyez** [comment]
any updates @StatKumar  ?
