### ISSUE TITLE
feat: add support for python venv

### ISSUE THREAD

**Issue by bryce-seefieldt** [neokd/NeoGPT#110]
Can you also add support for python venv?

_Originally posted by @neokd in https://github.com/neokd/NeoGPT/issues/88#issuecomment-1788529996_
            
Hi, apologies for letting some time pass on this.  Wanted to confirm with you if this was still an issue you'd like addressed.  If so, just wanted to clarify the end goal.
I'm assuming you'd like a py virtual environment built that includes all the dependenciens and facilitates running the program without any additional build steps?

Can you confirm?
Thanks,
Bryce

**Comment by neokd** [comment]
@bryce-seefieldt this issue is been already solved.
