### ISSUE TITLE
Load Config for NeoGPT

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#112]
**Description:**
To enhance user experience, we need to implement a configuration loading function for NeoGPT. This function will read a YAML configuration file, parse its contents, and set up NeoGPT based on the stored configuration details.

**Load Config for NeoGPT**

1. Define a function load_config() to handle the loading process.
2. Read the YAML file containing the configuration details.
3. Parse the YAML content to retrieve the configuration parameters.
4. Set up NeoGPT with the loaded configuration, ensuring proper initialization.

**Comment by bryce-seefieldt** [comment]
Can you provide further details on what specifc config details should be included in the YAML file?  
At what stage in the setup/build process would the user be utilizing the config option? Is it a method of running the program once the DB has already been built? Would like to tackle this if you can elaborate on the details.
Thanks,
Bryce

**Comment by neokd** [comment]
@bryce-seefieldt the YAML would include 

1. Capture NeoGPT-related details such as version, environment, persona, UI settings, model type, and export date.
2. Include model-specific information like model name, file, and embedding model.
3. Capture database details, including the parent directory.
4. Include directory information, such as the source directory and workspace directory.
5. Capture memory configurations, including the default memory key.

As mentioned in #111 . You can allow users to have multiple configs allowing them to customise based on their needs.

**Comment by bryce-seefieldt** [comment]
OK thanks, can I work on this ?
- Just so I am certain,  running load_config() will need to include running/re-running the builder if config files details  differ from the users current build, correct?
- I may have some questions on how/where certain details are saved in the program but I'll let you know.

**Comment by neokd** [comment]
These config are just for NeoGPT main file and not for builder.

**Comment by Tanishka2712** [comment]
Hello! I want to enquire whether this issue is still around and can I start working on this under kwoc?

**Comment by bryce-seefieldt** [comment]
I am almost ready to submit a PR for this  issue.

**Comment by neokd** [comment]
> Hello! I want to enquire whether this issue is still around and can I start working on this under kwoc?

The issue is already in progress by @bryce-seefieldt

**Comment by Tanishka2712** [comment]
okayy!

**Comment by neokd** [comment]
@bryce-seefieldt any updates on the issue?

**Comment by bryce-seefieldt** [comment]
[PR 123](https://github.com/neokd/NeoGPT/pull/123) includes some updates to both import and export config functions.

**Comment by neokd** [comment]
Closing this issue for now
