### ISSUE TITLE
Ai-Chat bot 

### ISSUE THREAD

**Issue by SaiSravanthiChandana** [neokd/NeoGPT#125]
an AI-CHAT BOT should be added so that the user can have a conversation with the ai and can explain exactly what he wants...
using python code an AI-Chat bot code can be done in a clean way.

This can get more responsive by adding ai chatbot

**Comment by neokd** [comment]
It's already an AI bot with autonomous agents allowing users to chat with documents and only with the LLM also. To trigger that behaviour you can use `--mode llm` as the parameter when running it.

**Comment by SwastiShankhdhar** [comment]
> It's already an AI bot with autonomous agents allowing users to chat with documents and only with the LLM also. To trigger that behaviour you can use `--mode llm` as the parameter when running it.

I'LL LIKE TO WORK ON THIS ISSUE, PLEASE ASSIGN IT
