### ISSUE TITLE
Transition from colorama to rich for Improved Terminal Interaction

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#126]
In this issue, we are transitioning our application from using colorama to rich for enhanced terminal interaction. This transition involves locating and updating import statements, adjusting color codes, updating print statements, and ensuring consistent styling throughout the application.

### Steps to Reproduce:

1. Search and remove all import statements related to colorama (both direct imports and specific imports).
2. Update color codes from Fore, Back, or Style in colorama to the equivalent syntax in rich.
3. Modify print statements using colorama to the rich syntax.
4. Review and update styling for panels and prompts, replacing colorama styling with rich syntax.
5. Ensure the correct configuration of the rich console, removing any unnecessary code related to initializing or configuring colorama.
6. Thoroughly test the application to verify a successful transition, checking for consistent and desired styles.

**Comment by ayushmorbar** [comment]
Hey, I would like to work on this issue as part of JWoC’24

**Comment by neokd** [comment]
@ayushmorbar this issue is already solved. You can look at other issues or create a new one
