### ISSUE TITLE
Add PDF reader

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#135]
In [read_file.py](https://github.com/neokd/NeoGPT/blob/main/neogpt/utils/read_file.py) you need implement a PDF reader using LangChain. This will allow NeoGPT to read and process content from PDF files, enabling users to include PDF documents as part of their interactions with NeoGPT.

**Comment by ayushmorbar** [comment]
Hello, i would like to work on this issue as part of #JWoC

**Comment by ayushmorbar** [comment]
Hello, i would like to work on this issue as part of JWoC!

**Comment by neokd** [comment]
@ayushmorbar any updates?

**Comment by ayushmorbar** [comment]
Yeah, i understood the assignment and I'm on it.

**Comment by neokd** [comment]
You can refer here if facing any difficulties https://python.langchain.com/docs/modules/data_connection/document_loaders/pdf#using-pdfminer

**Comment by ayushmorbar** [comment]
okay thanks.

**Comment by ayushmorbar** [comment]
Implemented #158
