### ISSUE TITLE
Add '/save' magic command

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#136]
In [magic_commands.py](https://github.com/neokd/NeoGPT/blob/main/neogpt/utils/magic_commands.py) implement a `/save` command that will write the user history for a current session in a text file.

**Comment by pranjalipilankar** [comment]
please assign me this issue for JWOC

**Comment by neokd** [comment]
@pranjalipilankar assigned

**Comment by neokd** [comment]
@pranjalipilankar any updates?

**Comment by pranjalipilankar** [comment]
I am having some issues with requirements.txt. I am trying to resolve it. Will update by EOD today

**Comment by neokd** [comment]
What issue are u facing?

**Comment by pranjalipilankar** [comment]
![Screenshot 2022-12-21 082431](https://github.com/neokd/NeoGPT/assets/120120163/779eb33b-1d6f-47ae-aa4b-033cb4f444d4)

**Comment by pranjalipilankar** [comment]
![Screenshot 2024-01-30 141050](https://github.com/neokd/NeoGPT/assets/120120163/f87bcabe-07b9-4e5d-a538-1b768e7bf5dd)

**Comment by neokd** [comment]
@pranjalipilankar update your fork. The requirements are updated .
You can try `pip install pdfminer.six==20231228`

**Comment by ayushmorbar** [comment]
Done!

**Comment by neokd** [comment]
Closing issue, Thanks for the contribution

**Comment by ayushmorbar** [comment]
As an AIML enthusiast, i am happy to contribute my part in this amazing project of yours.
