### ISSUE TITLE
Add /history magic command

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#137]
In [magic_commands.py](https://github.com/neokd/NeoGPT/blob/main/neogpt/utils/magic_commands.py) implement a `/history` command that will display the previous conversations between NeoGPT and the user for the current session.

**Comment by Saloni0512** [comment]
Hey @neokd I would like to work on this issue under JWOC.

**Comment by neokd** [comment]
Sure, I have assigned it to you

**Comment by Saloni0512** [comment]
I'm working on the issue will create a pr by tomorrow for sure!

**Comment by ayushmorbar** [comment]
Hi,
I would like to try my hands on this issue as part of JWoC.
