### ISSUE TITLE
Add '/copy' command

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#139]
In [magic_commands.py](https://github.com/neokd/NeoGPT/blob/main/neogpt/utils/magic_commands.py)

Integrate `/copy` command  to streamline your interaction with NeoGPT in the project. This handy command facilitates the effortless copying of the latest response generated by NeoGPT directly to your clipboard. With just a simple command, users can access and utilize the model's output for various purposes, enhancing the overall usability of the project. The implementation is designed for a smooth and error-tolerant experience, ensuring users are promptly notified upon successful copying. Integrate this feature seamlessly into your workflow for enhanced productivity.

**Comment by ayushmorbar** [comment]
I would like to work on this issue as part of JWoC, so please assign me!

**Comment by ayushmorbar** [comment]
I would like to work on this issue now. Please, assign me

**Comment by neokd** [comment]
@ayushmorbar merged this one
