### ISSUE TITLE
Redo README

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#142]
Change the current readme and format it properly allowing user's to understand and have an overview of the project.

Use readme badges, tags ,etc to enhance the look of the file.

**Comment by AnamNaaz-7** [comment]
Please assign this issue to me under JWOC.

**Comment by AnamNaaz-7** [comment]
No. Pull request is still there. You can merge it.

**Comment by neokd** [comment]
Sure

**Comment by AnamNaaz-7** [comment]
Thankyou! :)
