### ISSUE TITLE
Intro to LLM 

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#146]
The current documentation for language models in NeoGPT lacks a clear structure, making it challenging for users to navigate and choose between local and hosted models. You need to populate the file [introduction.mdx](https://github.com/neokd/NeoGPT/blob/main/docs/language-models/introduction.mdx)

The file must contain the following 

- Introduction 
- A card to display offline models and hosted models (something like the image below but for LLM's)
![Screenshot 2024-01-23 at 8 51 05 PM](https://github.com/neokd/NeoGPT/assets/71772185/ac4bc0c8-eb2b-4a4c-9e03-f146db6fdacf)

**Comment by jayakedia10** [comment]
@neokd I would love to work on this. Can you please assign me this under JWOC'24?

**Comment by neokd** [comment]
@jayakedia10 assigned

**Comment by neokd** [comment]
@jayakedia10 any updates?

**Comment by Saloni0512** [comment]
Hey @neokd can I take up this issue, the previous issue was a bit difficult for me to solve hence I would like to try this one

**Comment by neokd** [comment]
@Saloni0512 assigned

**Comment by Saloni0512** [comment]
@neokd this issue was assigned to me just an hour back and someone has already submitted a pr without the issue being assigned to them.Kindly consider my pr as well. Thank you!

**Comment by neokd** [comment]
I'm not expecting anything like that. You can refer the image above and work accordingly. It should be basically have an introduction to LLM and what we support with cards redirecting to "Local Models" and "Hosted Models".

**Comment by Saloni0512** [comment]
Ok sure
