### ISSUE TITLE
Create UI for NeoGPT

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#15]
# UI
Create an basic UI like a chatbot like interface to interact with neogpt

**Comment by sukhmani1303** [comment]
hey! can you share more details about the type of interface or the preferred languages/ framework to use etc

**Comment by neokd** [comment]
@sukhmani1303 there aren't any specific framework or such for now. I just want to add an basic UI maybe using like streamlit or chainlit?

**Comment by neokd** [comment]
@bermr are you working on this issue?

**Comment by bermr** [comment]
Hi, I started but couldn't work more: here's the code so anyone can continue: https://github.com/neokd/NeoGPT/pull/52
