### ISSUE TITLE
Add hacker news loader

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#160]
In builder_helpers add a method to load hacker news url from the `builder.url` file

**Comment by neokd** [comment]
In the Builder Helper, there is a `load_web.py` module commonly employed for retrieving content from the web. Langchain offers specialized loaders designed for specific websites, ensuring that the obtained results are cleaner and free of unnecessary HTML elements. You need to use Hacker new loader to get content from ycombinators website

**Comment by ayushmorbar** [comment]
oh got it now, cool.
