### ISSUE TITLE
Docs: OpenAI API key 

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#163]
Users may face difficulties setting up their OpenAI API key to use the NeoGPT. We need clear and comprehensive documentation on obtaining and configuring the API key for both Windows and MacOS/Linux. Create a detailed guide in the documentation file [here](https://github.com/neokd/NeoGPT/blob/main/docs/guides/setup-openai-key.mdx) to help users with the API key setup process.

You can test the docs on this URL
http://localhost:3000/guides/setup-openai-key

**Comment by yashasvini121** [comment]
Hi @neokd , Could you please assign me this issue under JWOC?
