### ISSUE TITLE
 Add `/help` Command to `magic_commands.py`

### ISSUE THREAD

**Issue by ayushmorbar** [neokd/NeoGPT#173]
The magic_commands.py script lacks a /help command that would list all available commands for the user. This enhancement would improve user experience by providing an easy way to view all commands. The /help command should list all commands with a brief description of their functionality.

-------------------------------------------------------------------------------------------------------------------------------------------------
**Is your feature request related to a problem? Please describe.**

Users currently have no way of knowing all the available commands in the `magic_commands.py` script without looking at the source code or documentation.

**Describe the solution you'd like**

I would like a `/help` command to be added to the `magic_commands.py` script. This command should list all available commands along with a brief description of their functionality.

**Describe alternatives you've considered**

An alternative could be to include a comment at the top of the `magic_commands.py` script that lists all the commands. However, this would not be as user-friendly as a `/help` command.

**Additional context**

This enhancement would improve the user experience by providing an easy way to view all commands without needing to refer to the documentation or source code.

**Comment by neokd** [comment]
This would be a good addition

**Comment by ayushmorbar** [comment]
I'll get on this as soon as i complete it since its too easy. Beside this, I've got some amazing commands and features which we can integrate like a text-to-speech module, etc. I will create the issues soon!

**Comment by neokd** [comment]
That's great
