### ISSUE TITLE
Create a chat interface 

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#176]
To design an interactive user interface for NeoGPT using Streamlit, you will need to create a     
basic chat interface. This can be accomplished by writing code within the ui.py file located within the neogpt folder. 
The code should allow users to interact with NeoGPT through this UI.

**Comment by Saloni0512** [comment]
I would like to try this issue under jwoc

**Comment by Saloni0512** [comment]
Hey @neokd  what additions do you exactly want in the chat interface ? Like can I go for a sidebar that contains options for uploading files and clearing chat history.

**Comment by neokd** [comment]
Yeah that will be enough

**Comment by Saloni0512** [comment]
Hey @neokd sorry for the delay I will push the pr by tomorrow
morning.
