### ISSUE TITLE
Cost Callback Handler

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#185]
Create a function called `calculate_togetherai_cost()` in TokenCallbackHandler in [callback_handler.py ](https://github.com/neokd/NeoGPT/blob/main/neogpt/callback_handler.py) the function should accept the number of generated tokens as the input and return the calculated cost as the output

**Comment by ayushmorbar** [comment]
Assign me under #JWoC for this issue

**Comment by ayushmorbar** [comment]
DONE

**Comment by ayushmorbar** [comment]
Solved, please do review the PR.
