### ISSUE TITLE
Re: Implement the export config functionality properly

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#193]
The current export-config feature in the config.py module exhibits unexpected behavior. Consider implementing an alternative mechanism for exporting configuration settings to ensure its proper functionality. Also add `/export` magic command to export the settings.

**Comment by yashasvini121** [comment]
Hey @neokd, Could you assign me this issue under JWOC?

**Comment by neokd** [comment]
> Hey @neokd, Could you assign me this issue under JWOC? Also I am really sorry about the delay I caused in my previously assigned issue.

Thats okay. Update the changes for this issue.

**Comment by neokd** [comment]
Merged
