### ISSUE TITLE
Budget Manager

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#197]
In the `budget_manager.py` file, implement code within the `budget_manager` function to compute the budget and update the `TOTAL_COST`. In the chat session, if a user sets a maximum budget and surpasses it, gracefully conclude the session with a message indicating that the budget has been exceeded.

**Comment by ayushmorbar** [comment]
Hi, Assign me this issue as part of JWOC

**Comment by ayushmorbar** [comment]
Could you explain more on this issue, like what am i supposed to do exactly?

**Comment by ayushmorbar** [comment]
Understood

**Comment by neokd** [comment]
Un assigning!
