### ISSUE TITLE
Writer Assistant Write to a file

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#205]
In the [writer_assistant.py](https://github.com/neokd/NeoGPT/blob/main/neogpt/utils/writer_assistant.py) file, enhance the function by adding a parameter, `code`, which, when set to `False`, writes the content to a file. If set to `True`, it should write the content to a file with a `.py` extension.

**Comment by ayushmorbar** [comment]
Hey,

I've solved this issue since I find it's easy as part of JWoC and also meanwhile while I am working on the assigned issue.
