### ISSUE TITLE
custom exit message on ctrl+c

### ISSUE THREAD

**Issue by yashasvini121** [neokd/NeoGPT#207]
**What would you like to be added**:
A try and except block for handling keyboardInterrupt i.e. `ctrl+c`

**Why is this needed**:
Currently pressing ctrl+c simply exits the program. It would look better to have a custom exit message
![image](https://github.com/neokd/NeoGPT/assets/100478608/2b47c6d2-08ff-4e1f-b570-50184208288b)

**Comment by neokd** [comment]
Merged
