### ISSUE TITLE
Add `/search [keyword]` Magic Command to Search Chat History

### ISSUE THREAD

**Issue by ayushmorbar** [neokd/NeoGPT#210]
**Is your feature request related to a problem? Please describe.**

Yes, currently there is no way to quickly search for specific keywords in the chat history. This can be frustrating when trying to recall specific parts of a conversation.

**Describe the solution you'd like**

I would like a new magic command `/search [keyword]` to be added. This command should search the chat history for a specific keyword and return all messages containing that keyword.

**Describe alternatives you've considered**

An alternative could be to manually scroll through the chat history, but this can be time-consuming and inefficient, especially for long chat sessions.

**Additional context**

This feature would greatly enhance the user experience by providing a quick and easy way to retrieve specific parts of the conversation.

**Comment by neokd** [comment]
Can you explain how are you planning to add it

**Comment by ayushmorbar** [comment]
Sure, here's the plan:

1. We will modify the magic_commands function in the magic_commands.py file.
2. We will add a new condition to check if the user input starts with /search.
3. If it does, we will extract the keyword from the user input.
4. We will then iterate over the chat history, which is stored in chain.combine_documents_chain.memory.chat_memory.messages.
5. For each message in the chat history, we will check if the keyword is in the message content.
6. If it is, we will print the message.
7. If no messages are found with the keyword, we will print a message saying "No messages found with the provided keyword."

**Comment by neokd** [comment]
@ayushmorbar are you working on. this?

**Comment by neokd** [comment]
Okay okay.
