### ISSUE TITLE
Lazy Imports 

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#214]
Refactor the utility module to implement lazy imports, which will help minimize startup time by loading only the required modules when they are actually needed.

**Comment by SwastiShankhdhar** [comment]
> Refactor the utility module to implement lazy imports, which will help minimize startup time by loading only the required modules when they are actually needed.

I WANT TO WORK ON THIS ISSUE , PLEASE ASSIGN IT

**Comment by neokd** [comment]
Currently we are working on the V0.2 which is in development you can check those out.
