### ISSUE TITLE
README 

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#22]
# Change in README

### Issue Description
Provide a brief description about the project and its features with installation steps.

**Comment by Abhishekgupta204** [comment]
Please assign me this issue.

**Comment by Abhishekgupta204** [comment]
@neokd 
Should I also add more about Hacktoberfest as this repository is open for Hacktoberfest. Information on Hacktoberfest and its website will help beginners understand and register for the same.

**Comment by neokd** [comment]
We already have an readme with hacktoberfest , you can edit the current one and make it more detailed.

**Comment by SuryaCreatX** [comment]
Can you please assign me this issue too?
