### ISSUE TITLE
Load Hugging face models 🤗

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#27]
In the load_model() add support for loading full models from huggingface directly. For hardware supported devices.

**Comment by dikshant182004** [comment]
hii @neokd plz assign this issue to me.

**Comment by neokd** [comment]
@dikshant182004 done

**Comment by dikshant182004** [comment]
hii @neokd does i need to add this feature in prompt.py

**Comment by neokd** [comment]
No, for now just in load_model()

**Comment by dikshant182004** [comment]
does it is present in builder.py

**Comment by neokd** [comment]
No

**Comment by dikshant182004** [comment]
or the load model () funtion that u have made in main .py

**Comment by neokd** [comment]
In the load_model() that is there in [main.py ](https://github.com/neokd/NeoGPT/blob/main/main.py#L54)

**Comment by dikshant182004** [comment]
okay I got it .Thanx for the help

**Comment by dikshant182004** [comment]
hii @neokd i have made some changes in issue #27.plz have a look at it
