### ISSUE TITLE
Add pinecone support for the vectorstore

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#28]
# Description

Add support for pinecone for storing the vectors and using with RAG

**Comment by dikshant182004** [comment]
hii @ plz assign this issue to me .I will Add pinecone support for the vectorstore

**Comment by neokd** [comment]
@dikshant182004 Sure

**Comment by dikshant182004** [comment]
hii @neokd i want to ask something .Do I need to add that pinecone support in that main.py file only .

**Comment by neokd** [comment]
No. You need to just create an file in vectorstore to load pinecone. Later i'll create an issue to integrate with builder.py and main.py

**Comment by dikshant182004** [comment]
okay , by mistake i have updated that it in main.py

**Comment by dikshant182004** [comment]
i have added a pinecone file to the best of  my knowledge and documentation .plz have a look at it
