### ISSUE TITLE
Add support for GPTQ

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#3]
Add support for GPTQ models when loading a model in load_model()

**Comment by VPraharsha03** [comment]
Could you please assign me on this ?

**Comment by neokd** [comment]
Yeah sure

**Comment by neokd** [comment]
@VPraharsha03 Any updates on the issue?

**Comment by VPraharsha03** [comment]
@neokd I'm working on another issue, will keep you updated

**Comment by neokd** [comment]
Okayy

**Comment by VPraharsha03** [comment]
@neokd Should `AutoModelForCausalLM.from_pretrained` method be used or `GPTQModel.from_pretrained` ?

**Comment by neokd** [comment]
You can use AutoGPTQ for loading GPTQ models for now

**Comment by VPraharsha03** [comment]
@neokd Thank you, Can I get a hacktoberfest accepted label ?
