### ISSUE TITLE
Output parser

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#30]
# Output parser for structured output

Add an output parser for the LLM to display an structured output in JSON or any other format.

**Comment by avi-dey** [comment]
Hello @neokd . Can I start working on this?

**Comment by neokd** [comment]
Go Ahead @avi-dey

**Comment by neokd** [comment]
@avi-dey any updates on the issue?

**Comment by avi-dey** [comment]
I couldn't run it. It takes around 2-3  minutes to reply and when I give it some tasks it replies with "!" , "how", "how may i", etc. After spending a lot of time I couldn't make it work and became frustrated.
requirements.txt was missing these 3 packages: auto_gptq, youtube-transcript-api, pytube.
Can you please guide me what all it can do at the moment?

**Comment by neokd** [comment]
@avi-dey  any updates on the issue?
