### ISSUE TITLE
Embedding model loads twice in builder

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#31]
The embedding model loads twice in the vectorstore director. Decreasing the performance for the same.

**Comment by bermr** [comment]
Hey, want to help with this issue. Is this a good solution? https://github.com/neokd/NeoGPT/pull/37

**Comment by neokd** [comment]
@bermr the embedding model is already passed in the respective db so for now we can just remove the embedding code from main.py and builder.py

**Comment by bermr** [comment]
Ok. Just added a new commit to the PR.

**Comment by neokd** [comment]
@bermr I'll check and merge it
