### ISSUE TITLE
Add "how to run" section to README

### ISSUE THREAD

**Issue by bermr** [neokd/NeoGPT#38]
Create a section explaining how to run the model. 
Explain that Google CSE and API Key are needed, which command use to run, etc.

**Comment by neokd** [comment]
@bermr can you describe what are you trying to add

**Comment by bermr** [comment]
Hi. Actually seen this issue: https://github.com/neokd/NeoGPT/issues/15, and i think that implementing the UI would be a better solution

**Comment by neokd** [comment]
Great! You going to build it with?

**Comment by bermr** [comment]
Yes, if nobody implements until the weekend i will try
