### ISSUE TITLE
Create a Beginner's Guide

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#40]
Write a guide or tutorial aimed at helping beginners get started with the project. Share your knowledge and make it easy for newcomers to dive in.

**Comment by AidenW8512** [comment]
Can I be assigned?

**Comment by neokd** [comment]
Assigned

**Comment by AidenW8512** [comment]
Thank you, here's the summary for the Beginners:

1. From your GitHub profile, go to Your Repositories after you sign in with your GitHub Account
2. Create a New Repository and fill in the repository details & additional files and settings
3. You can clone the repository if you’d like to work locally
4. Now that the new repository is created, you can start working on your project by adding files, codes, etc to your project
5. You can also add collaborators to work on the project with you

**Comment by AidenW8512** [comment]
I added my code to the main branch, can you see it?

**Comment by neokd** [comment]
Create a pull request
