### ISSUE TITLE
Create Shell Script for Easy Execution

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#43]
Develop a shell script (e.g., a Bash script) that simplifies the process of running NeoGPT by executing the necessary commands and options. This script should allow users to quickly start NeoGPT without needing to remember complex command-line arguments.

**Comment by Mohitraut07** [comment]
can I try this

**Comment by neokd** [comment]
@Mohitraut07 yeah sure

**Comment by bryce-seefieldt** [comment]
I have been experimenting with some solutions to this issue. Hoping I can create a PR to review my approach.  If so, just had some questions before proceeding.
1. Where would you like the .sh file to be saved within the directory?
2.  What assumptions can I make about the user's current environment when running the script?  Would you like assume that the user is setup to run the script from Anaconda Command Prompt?  
3.  Should we assume the user has already populated a builder.url file and/or added files to the document directory? Or do you want some kind of prompt to advise them  to do this prior to proceeding?

**Comment by neokd** [comment]
.sh should be in the root of the project. You can check users for python and proceed with that. Builder.url doesn't have any role if it's empty as there is no prbm. Builder.py will handle it.
