### ISSUE TITLE
Add Timer in the user input (main.py)

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#44]
If no input is received from the user for next 30 seconds or 1 minute then the loop should close automatically and the program should end.

**Comment by savyez** [comment]
Hey, I would like to work on this issue. Is it available?

**Comment by neokd** [comment]
@savyez yeah u can work on it

**Comment by savyez** [comment]
Hey, I am facing some issues in setting up the project. are there any means for connecting to you?

**Comment by neokd** [comment]
What kind of issue? are you facing. If it persist then i can connect via discord or gmeet

**Comment by Govind516** [comment]
I want to work on this issue. 
Please assign me this issue !

**Comment by neokd** [comment]
You can check out other issues @Govind516 since @savyez is already working on it. If this issue is active for more 3 days I'll assign it to u.

**Comment by savyez** [comment]
> What kind of issue? are you facing. If it persist then i can connect via discord or gmeet

Hey, I would like to join your Discord server. And @Govind516 brother, I am working on this issue I will let you know in three days whether I was able to add the feature or not. If I wasn't able to, I will happily hand it over to you.

**Comment by neokd** [comment]
> > What kind of issue? are you facing. If it persist then i can connect via discord or gmeet
> 
> Hey, I would like to join your Discord server. And @Govind516 brother, I am working on this issue I will let you know in three days whether I was able to add the feature or not. If I wasn't able to, I will happily hand it over to you.

You can join the server @ https://discord.gg/PC8Mq25E
