### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#48]
Implement Docker support to make it easier for users to deploy and run NeoGPT in various environments. Dockerization ensures consistent and isolated runtime environments, simplifying the setup process and enhancing portability.

Tasks:

1. Create a Dockerfile for NeoGPT.
2. Define the base image and required dependencies.
3. Configure the container to run NeoGPT with specific command-line arguments.
4. Provide clear instructions for building and running NeoGPT using Docker.

**Comment by Ymir-badam** [comment]
Will be working on it @neokd

**Comment by neokd** [comment]
@Ymir-badam thanks

**Comment by neokd** [comment]
@Ymir-badam Any updates on this issue?

**Comment by neokd** [comment]
@Ymir-badam  Any updates on the issue?

**Comment by zakhaev26** [comment]
Hey @neokd , I have some experience with Docker and I would like to contribute in this project under Hacktoberfest.Can you please assign this issue to me?

**Comment by neokd** [comment]
@zakhaev26 assigned

**Comment by zakhaev26** [comment]
While installation, i am getting error logs when installing dependencies :

```cmd
Building wheels for collected packages: llama_cpp_python
  Building wheel for llama_cpp_python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama_cpp_python (pyproject.toml) did not run successf
ully.
  │ exit code: 1
  ╰─> [20 lines of output]
```

```cmd
 CMake Error at CMakeLists.txt:3 (project):
        No CMAKE_C_COMPILER could be found.
     
     
     
      CMake Error at CMakeLists.txt:3 (project):
        No CMAKE_CXX_COMPILER could be found.



      -- Configuring incomplete, errors occurred!

      *** CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama_cpp_python
Failed to build llama_cpp_python
ERROR: Could not build wheels for llama_cpp_python, which is required to install pyproject.toml-based pro
jects
```

I think the second one is related with CMake not present in my machine , but i still have no idea about the 1st log.
Can You please rectify them? @neokd

**Comment by neokd** [comment]
You need to install visual studio and install cmake from there.

**Comment by zakhaev26** [comment]
I have C++ installed but I guess it didn't had CMake. Installed it from their website.
Even tried on Visual Studio ,Still failing the dependency installation.
![image](https://github.com/neokd/NeoGPT/assets/119437069/0432580a-5b4b-4578-acd3-aaa0f906ba1e)

**Comment by neokd** [comment]
You can have a look at https://github.com/abetlen/llama-cpp-python/issues/233
