### ISSUE TITLE
Specify required Python version

### ISSUE THREAD

**Issue by AndreasWintherMoen** [neokd/NeoGPT#49]
Currently, the application doesn't run on Python < 3.10, and Python > 3.10 doesn't work due to incompatibilities with PyTorch.

**Comment by neokd** [comment]
It works on python 3.10

**Comment by AndreasWintherMoen** [comment]
Yep, exactly. That should be mentioned in the readme.

**Comment by neokd** [comment]
You can change it @AndreasWintherMoen

**Comment by AndreasWintherMoen** [comment]
Not sure. I checked out the project to contribute to hacktoberfest, but couldn't because of a mismatching Python version. To be a hacktoberfest contribution the issue must have the hacktoberfest tag, right?

**Comment by neokd** [comment]
Add the tag
