### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#5]
Add documentation for the project

**Comment by abuharish02** [comment]
Could you please assign me so i can work on this ?

**Comment by neokd** [comment]
Yeah sure

**Comment by abuharish02** [comment]
Could you please give me some hint so I can work because I can see a readme file is already present ?

**Comment by neokd** [comment]
You need to add basic documentation in a file. for example below
<img width="583" alt="Screenshot 2023-10-02 at 12 28 52 PM" src="https://github.com/neokd/NeoGPT/assets/71772185/c379fc10-73da-4505-84d9-92637a88f2f8">

**Comment by neokd** [comment]
@abuharish02 any updates on the issue?

**Comment by abuharish02** [comment]
@neokd I can see document uploader from specific path is already present in builder.py file.

**Comment by neokd** [comment]
This issue is to make a clear concise documentation about the entire project and how it works. 

starting from builder.py and functions in it extending it till main.py. Allowing users to know about specific functions and what they do.

**Comment by neokd** [comment]
@abuharish02 are you working on it?

**Comment by abuharish02** [comment]
@neokd Due to time constrain I am unable to work. You can assign to someone else.
