### ISSUE TITLE
Setup via Ananconda or MiniConda

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#51]
Add steps to setup the project via Ananconda in the readme

**Comment by vbhasin999** [comment]
Hi, I'm interested in contributing, just to clarify this step: 'pip install -r requirements.txt' needs to be changed to use conda instead of pip?

**Comment by neokd** [comment]
We are using anaconda just to have a specific python version across all the platform and devices to avoid any compatibility issues.

You can add steps of how to install python with conda and then installating the requirements.txt
