### ISSUE TITLE
Make the code modular

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#57]
Since the main.py is getting long and affecting the overall readability and functionality of the project.I was thinking to make the code more modular into different files.

**Comment by PentW0lf** [comment]
We can make two module of StreamingStdOutCallbackHandler and TokenCallbackHandler class and i suggest you to keep function(load_model, db_retriver) there as it is... i would like to work on it !

**Comment by neokd** [comment]
Good Idea! i'm currently working on it. You can also Join me.

**Comment by neokd** [comment]
Accidentally closed the issue. Sorry for the glitch

**Comment by PentW0lf** [comment]
No issue, I'll start working on it as soon as possible.

**Comment by neokd** [comment]
Yeah Sure @PentW0lf

**Comment by PentW0lf** [comment]
Hey @neokd, 
There are some modules in main.py which are not being used, should i remove or keep it?

**Comment by neokd** [comment]
Which are those?

**Comment by PentW0lf** [comment]
At line 2 'torch' is imported and at line 138, you used it but some how you commented that line.

**Comment by neokd** [comment]
Yeah u can remove that

**Comment by neokd** [comment]
You can refer #60  for more details

**Comment by PentW0lf** [comment]
Hey,
can i do same modularization as i have done like main.py, i can't promise for #60

**Comment by neokd** [comment]
for `builder.py` i'm in progress of adding more functionality. Once we have added all the functionality we can update the code

**Comment by PentW0lf** [comment]
> for `builder.py` i'm in progress of adding more functionality. Once we have added all the functionality we can update the code

Take your time, I can do it after hfest too, No issue.

**Comment by neokd** [comment]
@PentW0lf thanks a lot
