### ISSUE TITLE
CLI documentation

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#59]
NeoGPT uses several CLI commands allowing users to customise its behaviour.

Make a .md file providing a brief documentation of the CLI and how to run and expected behaviour of NeoGPT. Making it easier for others to customise the project based on their needs.

**Comment by Ethaaan11** [comment]
@neokd could i be assigned to this task please?

**Comment by neokd** [comment]
@Ethaaan11 assigned

**Comment by neokd** [comment]
@Ethaaan11 any updates on the issue?
