### ISSUE TITLE
Add ISSUE TEMPLATE AND PULL REQUEST TEMPLATE

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#6]
add a template for full request and issue template in .github

**Comment by Chandak-Keshav** [comment]
Kindly assign me this @neokd

**Comment by kat-kan** [comment]
I also can work on this if @Chandak-Keshav decides not to, I have experience with creating such templates :)

**Comment by neokd** [comment]
@Chandak-Keshav you can work on the issue
