### ISSUE TITLE
Add function to write logs to a file.

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#67]
Add a function in builder.py to write all the logs to a file for inspection.

**Comment by bryce-seefieldt** [comment]
I would love to try and work through this issue. Trying to round out my first Hacktoberfest on some cool projects with some tasks within my wheelhouse.  This looks perfect.

**Comment by neokd** [comment]
@bryce-seefieldt sure you can work on it

**Comment by bryce-seefieldt** [comment]
Curious if you wanted all logs written to file but also maintain the current functionality log to console stdout ?

**Comment by neokd** [comment]
Sorry but @bryce-seefieldt the issue was solved .... You can check the PR. 

Checkout other open issues and features that you can implement in neogpt

**Comment by y9rabbito** [comment]
> Sorry but @bryce-seefieldt the issue was solved by @y9rabbito You can check the PR. 
@neokd could you please take your time to check the pull request if it's okk or to make any changes
