### ISSUE TITLE
Tqdm loader

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#72]
In builder.py add tqdm loader showing progress. Allowing users to see progress of documents getting ingested into the vectorstore when loading large files

**Comment by PentW0lf** [comment]
I would like to work on it but i need more info about this issue like where need to apply tqdm and some more if there anything else.

**Comment by neokd** [comment]
@PentW0lf 

When we run builder a loader like animation should come showing the progress of number of files in `documents` directory converted into vectors. Also you can extend this for URL's too.

**Comment by PentW0lf** [comment]
@neokd 
Do you mean 'docs' directory ??

**Comment by neokd** [comment]
I mean documents folder which is there in neogpt folder

**Comment by PentW0lf** [comment]
> I mean documents folder which is there in neogpt folder

Gotcha, gimme some time.

**Comment by neokd** [comment]
@PentW0lf yeah sure

**Comment by PentW0lf** [comment]
I'm bit confuse that where to show progress animation.

look:
![ss (2)](https://github.com/neokd/NeoGPT/assets/31568025/cc78d7c2-0716-4cef-8296-19cdbb7d7d9a)

do you want animation in progress of between max_seq_length 512 and last two line which is conversion into vectors (correct me if I'm wrong)  or just file count like Loading document or Loading batch etc...

**Comment by neokd** [comment]
You can show it After `Loading document batch` as one progress bar.
