### ISSUE TITLE
Update docs with docusaurus

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#75]
We recognize the importance of comprehensive documentation for our project, and we are taking steps to improve it. This issue is dedicated to adding documentation using Docusaurus that will enhance the accessibility and quality of our project's documentation.

Currently there are no such documentation rather than just readme files for running and builder.md to run youtube URL's

**Comment by Saurabhyadav0** [comment]
can you assing me this project

**Comment by neokd** [comment]
@Saurabhyadav0 assigned

**Comment by neokd** [comment]
@Saurabhyadav0 any updates?

**Comment by neokd** [comment]
@Saurabhyadav0 any update on the issue?
