### ISSUE TITLE
Docker: Unable to build the docker image. 

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#79]
Unable to run the docker image properly. It gives error when installing the requirements
<img width="1150" alt="Screenshot 2023-10-31 at 1 45 07 AM" src="https://github.com/neokd/NeoGPT/assets/71772185/38307cd9-2f74-492e-967f-6aa8dc21bc2a">

**Comment by ha36d** [comment]
Can I work on this issue?

**Comment by neokd** [comment]
@ha36d yes

**Comment by neokd** [comment]
Does the image build when running `auto-gptq==0.3.2` or did u change the version? bcoz i'm still getting the error

**Comment by neokd** [comment]
Great then can u rename the requirements to dev-requirement.txt
