### ISSUE TITLE
UI: streamlit persona selection

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#83]
NeoGPT allows user to specify a persona `"default", "recruiter", "academician", "friend", "ml_engineer", "ceo", "researcher"`. Add a select box in the sidebar allowing users to select a persona according to their requirement.

**Comment by kehsihba19** [comment]
Hi @neokd, can this issue be assigned to me?
Rough design attached:


<img width="1725" alt="Screenshot 2023-11-01 at 4 12 59 PM" src="https://github.com/neokd/NeoGPT/assets/44729252/61237985-9846-4ff9-9b16-6ba590a2eab9">
<img width="1722" alt="Screenshot 2023-11-01 at 4 12 23 PM" src="https://github.com/neokd/NeoGPT/assets/44729252/4b74fec7-3ca0-4595-9f5e-7f781ab03884">
<img width="1728" alt="Screenshot 2023-11-01 at 4 12 46 PM" src="https://github.com/neokd/NeoGPT/assets/44729252/ff5b4565-f41a-45e6-a96e-f84c3314e24d">

**Comment by neokd** [comment]
@kehsihba19  assigned
