### ISSUE TITLE
Including developer docs for working with Docker

### ISSUE THREAD

**Issue by zakhaev26** [neokd/NeoGPT#84]
# Issue Template for Hacktoberfest 2023 Contribution

### Issue Description
Provide a brief description of the issue you'd like to address. This can be a bug report, feature request, or any other improvement.

The current README.md doesn't define the procedure to work with Dockerfile and Containers to run NeoGPT.
### Expected Behavior
Explain what you expect to happen when this issue is resolved.
Not Applicable
### Current Behavior
Describe the current behavior of the project, which is affected by this issue.
Not Applicable
### Steps to Reproduce (if applicable)
If this is a bug report, provide a step-by-step guide to reproduce the issue.
Not Applicable
### Suggested Solution (if known)

Providing helpful note on using Dockerfile to create images and run containers.
### Your Environment (if applicable)
- Operating System:
- Browser (if relevant):
- Any other relevant information:

### Additional Context
Add any other context or information about the issue here.

### Your Contribution (For Pull Requests)
If you plan to contribute to this issue with a pull request, please outline your proposed changes and mention any related issues or pull requests.

### Acknowledgment (For Contributors)
By creating this issue or pull request, you acknowledge that you have read and agree to follow the [Code of Conduct](link-to-your-code-of-conduct) for this project.

---

Please follow this template to create a new issue for the [neokd/NeoGPT](https://github.com/neokd/NeoGPT) repository. Thank you for your contribution to Hacktoberfest 2023!

**Comment by neokd** [comment]
@zakhaev26 we can add this to readme once #82 gets solved bcoz there is error when building the file

**Comment by savyez** [comment]
Isn't this issue solved?
