### ISSUE TITLE
Docker build test with Github actions

### ISSUE THREAD

**Issue by ha36d** [neokd/NeoGPT#87]
# Issue Template for Hacktoberfest 2023 Contribution

### Issue Description
There is a need of Github actions, mostly for now, for testing python packages by creating the docker image.

### Expected Behavior
Stability of docker image.

### Current Behavior
Not stable for the moment.

### Steps to Reproduce (if applicable)
Creating an docker image with the dockerfile

### Suggested Solution (if known)
Having a pipeline with Github Actions.

**Comment by neokd** [comment]
yes you can work on it

**Comment by neokd** [comment]
You can work on it .
