### ISSUE TITLE
Add timed input

### ISSUE THREAD

**Issue by neokd** [neokd/NeoGPT#93]
add input timer in manager.py which closes the input after a particular amount of time and terminates the program.

**Comment by savyez** [comment]
Can you Explain this issue a bit? seems like #70 . Am I correct?

**Comment by neokd** [comment]
Yes it is similar to that

**Comment by savyez** [comment]
yeah, I can work on this issue if available.

**Comment by neokd** [comment]
Yes sure

**Comment by neokd** [comment]
@savyez are you working on this issue?

**Comment by savyez** [comment]
> @savyez are you working on this issue? 

I was working on this till Diwali, after that I haven't touch the computer yet, will commit the changes once it is done(give me 2 days).

**Comment by neokd** [comment]
@savyez sure

**Comment by savyez** [comment]
@neokd  I have opened the PR, please read the **current** behaviour and review the code. if there are any errors, do let me know on DC.
